### ISSUE TITLE
新电脑！

### ISSUE THREAD

**Issue by Qubik65536** [Cubik65536/Cubik65536#6]
新电脑！MacBook Pro 14 英寸 M2 Pro 10 核 CPU，16 核 GPU, 32GB + 1TB

![0](https://user-images.githubusercontent.com/72877496/230487627-97003b43-fc25-4b72-bd30-85d483541d9a.jpg)
![1](https://user-images.githubusercontent.com/72877496/230487428-a7947870-ddf9-4646-aa9c-1012dc9ed3a8.jpg)

**Comment by WUTONK** [comment]
32GB后期可能有点不够用

**Comment by WUTONK** [comment]
不过总比我的好，我只有8G😅

**Comment by Qubik65536** [comment]
> 32GB后期可能有点不够用

我这个 CPU 最多只能选 32G
